### ISSUE TITLE
Bug when i try to start gulp command

### ISSUE THREAD

**Issue by dtrujo** [tmaximini/ionic-gulp-seed#6]
Hi! i had installed this project using yo generator. When i finish to install all dependency package and i try yo start the project using gulp or gulp --build i found this error message:

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at requireFn (/Users/diegotrujillo/Documents/Ionic/test/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.defineProperty.get (/Users/diegotrujillo/Documents/Ionic/test/node_modules/gulp-load-plugins/index.js:59:18)
    at Object.<anonymous> (/Users/diegotrujillo/Documents/Ionic/test/gulpfile.js:244:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I have not idea how to fix it, can you help me?

Thanks in advance

**Comment by tmaximini** [comment]
Seems that some packages have not installed properly. I just tried it on my machine with a fresh generated project and I am seeing
`fatal: unable to connect to github.com:`
As you can see on https://status.github.com/ Github is being DDoS'ed currently. Maybe try again later and make sure all packages (npm & bower) install properly.

**Comment by tmaximini** [comment]
I just tried it again and it should work fine now. Please give a short info if you got it working or not.

**Comment by rahulpnath** [comment]
I got the same error and after a long time figured that I had missed the single quotes around gulp

var gulp = require(**'gulp'**);

Just in case some one else reaches here and this is the problem :)
